import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from '@typescript-eslint/eslint-plugin'
import tsparser from '@typescript-eslint/parser'
import prettierConfig from 'eslint-config-prettier'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // ── Ignored paths ────────────────────────────────────────────────────────
  // dist/ and node_modules/ are build artefacts.
  // src/components/ui/ is auto-generated by shadcn — never hand-edited.
  globalIgnores(['dist/**', 'node_modules/**', 'src/components/ui/**']),

  // ── Node.js config files ─────────────────────────────────────────────────
  // vite.config.ts, playwright.config.ts, eslint.config.js etc.
  // These run in Node, not the browser — need Node globals (process, __dirname).
  {
    files: ['*.config.ts', '*.config.js', '*.config.mts', '*.config.mjs'],
    languageOptions: {
      parser: tsparser,
      globals: {
        ...globals.node,
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
    },
    rules: {
      ...js.configs.recommended.rules,
      ...tseslint.configs.recommended.rules,
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },

  // ── Application source files ─────────────────────────────────────────────
  // Everything under src/ except the shadcn ui/ primitives (excluded above).
  {
    files: ['src/**/*.{ts,tsx}'],
    languageOptions: {
      parser: tsparser,
      globals: globals.browser,
    },
    plugins: {
      '@typescript-eslint': tseslint,
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...js.configs.recommended.rules,
      ...tseslint.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },

  // ── Prettier ─────────────────────────────────────────────────────────────
  // Must be last — turns off ESLint rules that conflict with Prettier formatting.
  prettierConfig,
])
